# end to end generation --------------------------------------------------------

pkg <- file.path(tempdir(), "devforge-generate-test")
unlink(pkg, recursive = TRUE)
dir.create(file.path(pkg, "inst", "params"), recursive = TRUE)
dir.create(file.path(pkg, "R"), recursive = TRUE)

writeLines(
  c(
    'spec_alpha <- param_spec(',
    '  name = "alpha",',
    '  title = "Wrapper function for alpha parameters",',
    '  fields = list(',
    '    k = p_int(15L, range = "[1,)", doc = "Number of neighbours."),',
    '    method = p_choice("kmknn", c("kmknn", "hnsw"), doc = "Which method.")',
    '  )',
    ')',
    '',
    'spec_beta <- param_defaults(',
    '  name = "beta_defaults",',
    '  title = "Helper function to generate beta defaults",',
    '  fields = list(tol = p_dbl(1, doc = "Tolerance."))',
    ')'
  ),
  file.path(pkg, "inst", "params", "params.R")
)

specs <- load_specs(pkg)
expect_equal(names(specs), c("alpha", "beta_defaults"))

paths <- forge_params(pkg, .verbose = FALSE)
expect_true(all(file.exists(paths)))
expect_equal(length(paths), 3L)

# the generated files load and behave
env <- new.env(parent = globalenv())
for (path in paths) sys.source(path, envir = env, keep.source = FALSE)
expect_equal(env$params_alpha(), list(k = 15L, method = "kmknn"))
expect_equal(env$params_beta_defaults(), list(tol = 1))
expect_true(isTRUE(env$checkAlphaParams(env$params_alpha())))
expect_false(isTRUE(env$checkAlphaParams(list(k = 0L, method = "kmknn"))))

# a defaults block declares no checker by default
expect_true(is.null(env$checkBetaDefaultsParams))

# every generated file carries the do-not-edit header
for (path in paths) {
  expect_equal(readLines(path)[1L], "# Generated by devforge. Do not edit.")
}

# the drift guard -----------------------------------------------------------------

expect_true(isTRUE(params_up_to_date(pkg)))

generated <- file.path(pkg, "R", "params-generated.R")
writeLines(c(readLines(generated), "# hand edit"), generated)
expect_equal(params_up_to_date(pkg), "R/params-generated.R")

forge_params(pkg, .verbose = FALSE)
expect_true(isTRUE(params_up_to_date(pkg)))

# a spec change that was never regenerated is caught too
writeLines(
  c(
    'spec_alpha <- param_spec(',
    '  name = "alpha",',
    '  title = "Wrapper function for alpha parameters",',
    '  fields = list(',
    '    k = p_int(30L, range = "[1,)", doc = "Number of neighbours.")',
    '  )',
    ')'
  ),
  file.path(pkg, "inst", "params", "params.R")
)
expect_true(is.character(params_up_to_date(pkg)))

unlink(pkg, recursive = TRUE)
