# generation -------------------------------------------------------------------

GENERATED_HEADER <- c(
  "# Generated by devforge. Do not edit.",
  "# Edit the specs under inst/params/ and run devforge::forge_params().",
  ""
)

#' A section divider padded to the 80 character line width
#'
#' @param title String. The section title.
#'
#' @returns String. The divider line.
#'
#' @keywords internal
section_header <- function(title) {
  checkmate::qassert(title, "S1")
  stem <- paste0("# ", title, " ")
  paste0(stem, strrep("-", max(1L, 80L - nchar(stem))))
}

GENERATED_FILES <- c(
  prelude = "R/params-prelude-generated.R",
  params = "R/params-generated.R",
  checkers = "R/checkmate-params-generated.R"
)

#' Group specs by the checker they declare
#'
#' @description Two specs may share a checker stem, in which case the checker
#' is emitted once. Their field sets have to agree, otherwise one of the two
#' constructors would be validated against the wrong shape.
#'
#' @param specs Named list of `devforge_spec` objects.
#'
#' @returns A list of `devforge_spec` objects, one per distinct checker stem,
#' in the order the stems first appear.
#'
#' @keywords internal
dedupe_checkers <- function(specs) {
  checkmate::assertList(specs, types = "devforge_spec")
  with_checker <- purrr::keep(specs, \(s) !is.null(s$checker))
  stems <- purrr::map_chr(with_checker, \(s) s$checker)
  purrr::map(unique(stems), \(stem) {
    group <- with_checker[stems == stem]
    shapes <- purrr::map(group, spec_field_names)
    if (length(unique(shapes)) > 1L) {
      stop(sprintf(
        "Specs %s share the checker `%s` but declare different fields.",
        paste(
          sprintf("`%s`", purrr::map_chr(group, \(s) s$name)),
          collapse = ", "
        ),
        stem
      ))
    }
    primary <- group[[1L]]
    primary$covers <- unname(purrr::map_chr(group, \(s) s$name))
    primary
  })
}

#' Render specs into the source of the generated files
#'
#' @param specs Named list of `devforge_spec` objects.
#'
#' @returns A named list of character vectors, one per entry of
#' `GENERATED_FILES`, without the generated header.
#'
#' @keywords internal
render_specs <- function(specs) {
  checkmate::assertList(specs, types = "devforge_spec", min.len = 1L)
  params <- purrr::map(specs, \(s) c(emit_ctor(s), ""))
  checkers <- purrr::map(
    dedupe_checkers(specs),
    \(s) c(emit_checker(s, specs), "")
  )
  list(
    prelude = emit_prelude(),
    params = c(
      section_header("parameter wrappers"),
      "",
      unlist(params, use.names = FALSE)
    ),
    checkers = c(
      section_header("parameter checkers"),
      "",
      unlist(checkers, use.names = FALSE)
    )
  )
}

#' Run air over a set of files
#'
#' @param paths Character vector of file paths.
#'
#' @returns `TRUE` if air ran, `FALSE` if it is not on the path.
#'
#' @keywords internal
run_air <- function(paths) {
  checkmate::assertFileExists(paths)
  if (!nzchar(Sys.which("air"))) {
    warning("`air` is not on the PATH. Generated files were left unformatted.")
    return(FALSE)
  }
  system2("air", c("format", shQuote(paths)), stdout = FALSE, stderr = FALSE)
  TRUE
}

#' Write rendered sources, format them and prepend the generated header
#'
#' @description air skips any file whose first line reads "Generated by", so
#' the header goes on after formatting, not before.
#'
#' @param rendered Named list of character vectors, as from [render_specs()].
#' @param paths Character vector of file paths, one per entry of `rendered`.
#'
#' @returns `paths`, invisibly.
#'
#' @keywords internal
write_generated <- function(rendered, paths) {
  checkmate::assertList(rendered, types = "character")
  checkmate::qassert(paths, sprintf("S%d", length(rendered)))
  purrr::walk2(rendered, paths, \(lines, path) writeLines(lines, path))
  run_air(paths)
  purrr::walk(paths, \(path) {
    writeLines(c(GENERATED_HEADER, readLines(path, warn = FALSE)), path)
  })
  invisible(paths)
}

#' Warn about generated lines that exceed the line width
#'
#' @description air will not reflow what a consumer's `persistent-line-breaks`
#' setting tells it to leave alone, and an unbreakable literal inside an
#' `extra_ctor` block cannot be reflowed at all. Say so rather than quietly
#' shipping a 95 character line into a package that formats at 80.
#'
#' @param paths Character vector of file paths.
#' @param width Integer. The line width. Defaults to `80L`.
#'
#' @returns `TRUE` if every line fits, `FALSE` otherwise.
#'
#' @keywords internal
warn_line_width <- function(paths, width = 80L) {
  checkmate::assertFileExists(paths)
  checkmate::qassert(width, "I1[1,)")
  over <- purrr::map(paths, \(path) {
    idx <- which(nchar(readLines(path, warn = FALSE)) > width)
    sprintf("  %s:%d", path, idx)
  })
  over <- unlist(over, use.names = FALSE)
  if (length(over) == 0L) {
    return(TRUE)
  }
  warning(
    sprintf(
      "Generated lines over %d characters:\n%s\nShorten them in the spec.",
      width,
      paste(over, collapse = "\n")
    ),
    call. = FALSE
  )
  FALSE
}

#' Generate the parameter wrappers and their checkmate extensions
#'
#' @description Reads every spec under `inst/params/`, writes the three
#' generated files under `R/` and formats them with air. The generated files
#' are meant to be committed.
#'
#' @param pkg String. Path to the package root. Defaults to `"."`.
#' @param .verbose Boolean. Report what was written. Defaults to `TRUE`.
#'
#' @returns Character vector of the paths written, invisibly.
#'
#' @export
forge_params <- function(pkg = ".", .verbose = TRUE) {
  checkmate::assertDirectoryExists(pkg)
  checkmate::qassert(.verbose, "B1")
  specs <- load_specs(pkg)
  rendered <- render_specs(specs)
  paths <- file.path(pkg, GENERATED_FILES[names(rendered)])
  write_generated(rendered, paths)
  warn_line_width(paths)
  if (.verbose) {
    message(sprintf(
      "Generated %d spec(s) into:\n%s",
      length(specs),
      paste0("  ", GENERATED_FILES[names(rendered)], collapse = "\n")
    ))
  }
  invisible(paths)
}

#' Check whether the generated files match the specs
#'
#' @description Regenerates into a temporary directory and compares. Meant for
#' CI, so that a hand-edit of a generated file or a spec change that was never
#' regenerated fails the build.
#'
#' @param pkg String. Path to the package root. Defaults to `"."`.
#'
#' @returns `TRUE` when everything matches, otherwise a character vector of the
#' paths that are out of date.
#'
#' @export
params_up_to_date <- function(pkg = ".") {
  checkmate::assertDirectoryExists(pkg)
  rendered <- render_specs(load_specs(pkg))
  tmp <- file.path(tempdir(), paste0("devforge-", as.integer(Sys.time())))
  dir.create(file.path(tmp, "R"), recursive = TRUE, showWarnings = FALSE)
  tmp_paths <- file.path(tmp, GENERATED_FILES[names(rendered)])
  write_generated(rendered, tmp_paths)
  stale <- purrr::keep(names(rendered), \(key) {
    live <- file.path(pkg, GENERATED_FILES[[key]])
    if (!file.exists(live)) {
      return(TRUE)
    }
    !identical(
      readLines(live, warn = FALSE),
      readLines(file.path(tmp, GENERATED_FILES[[key]]), warn = FALSE)
    )
  })
  unlink(tmp, recursive = TRUE)
  if (length(stale) == 0L) TRUE else unname(GENERATED_FILES[stale])
}
